// Code generated by mockery. DO NOT EDIT.

package mock_txcompressor

import mock "github.com/stretchr/testify/mock"

// TxMonitorer is an autogenerated mock type for the TxMonitorer type
type TxMonitorer struct {
	mock.Mock
}

type TxMonitorer_Expecter struct {
	mock *mock.Mock
}

func (_m *TxMonitorer) EXPECT() *TxMonitorer_Expecter {
	return &TxMonitorer_Expecter{mock: &_m.Mock}
}

// MonitorTxs provides a mock function with no fields
func (_m *TxMonitorer) MonitorTxs() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MonitorTxs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxMonitorer_MonitorTxs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MonitorTxs'
type TxMonitorer_MonitorTxs_Call struct {
	*mock.Call
}

// MonitorTxs is a helper method to define mock.On call
func (_e *TxMonitorer_Expecter) MonitorTxs() *TxMonitorer_MonitorTxs_Call {
	return &TxMonitorer_MonitorTxs_Call{Call: _e.mock.On("MonitorTxs")}
}

func (_c *TxMonitorer_MonitorTxs_Call) Run(run func()) *TxMonitorer_MonitorTxs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TxMonitorer_MonitorTxs_Call) Return(_a0 error) *TxMonitorer_MonitorTxs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxMonitorer_MonitorTxs_Call) RunAndReturn(run func() error) *TxMonitorer_MonitorTxs_Call {
	_c.Call.Return(run)
	return _c
}

// NewTxMonitorer creates a new instance of TxMonitorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxMonitorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxMonitorer {
	mock := &TxMonitorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
