// Code generated by mockery. DO NOT EDIT.

package synchronizer

import (
	context "context"
	big "math/big"

	common "github.com/ethereum/go-ethereum/common"

	etherman "github.com/0xPolygon/zkevm-bridge-service/etherman"

	mock "github.com/stretchr/testify/mock"
)

// storageMock is an autogenerated mock type for the storageInterface type
type storageMock struct {
	mock.Mock
}

type storageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *storageMock) EXPECT() *storageMock_Expecter {
	return &storageMock_Expecter{mock: &_m.Mock}
}

// AddBackwardLET provides a mock function with given fields: ctx, backwardLET, dbTx
func (_m *storageMock) AddBackwardLET(ctx context.Context, backwardLET *etherman.BackwardLET, dbTx interface{}) error {
	ret := _m.Called(ctx, backwardLET, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddBackwardLET")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.BackwardLET, interface{}) error); ok {
		r0 = rf(ctx, backwardLET, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_AddBackwardLET_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBackwardLET'
type storageMock_AddBackwardLET_Call struct {
	*mock.Call
}

// AddBackwardLET is a helper method to define mock.On call
//   - ctx context.Context
//   - backwardLET *etherman.BackwardLET
//   - dbTx interface{}
func (_e *storageMock_Expecter) AddBackwardLET(ctx interface{}, backwardLET interface{}, dbTx interface{}) *storageMock_AddBackwardLET_Call {
	return &storageMock_AddBackwardLET_Call{Call: _e.mock.On("AddBackwardLET", ctx, backwardLET, dbTx)}
}

func (_c *storageMock_AddBackwardLET_Call) Run(run func(ctx context.Context, backwardLET *etherman.BackwardLET, dbTx interface{})) *storageMock_AddBackwardLET_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*etherman.BackwardLET), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_AddBackwardLET_Call) Return(_a0 error) *storageMock_AddBackwardLET_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_AddBackwardLET_Call) RunAndReturn(run func(context.Context, *etherman.BackwardLET, interface{}) error) *storageMock_AddBackwardLET_Call {
	_c.Call.Return(run)
	return _c
}

// AddBlock provides a mock function with given fields: ctx, block, dbTx
func (_m *storageMock) AddBlock(ctx context.Context, block *etherman.Block, dbTx interface{}) (uint64, error) {
	ret := _m.Called(ctx, block, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddBlock")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.Block, interface{}) (uint64, error)); ok {
		return rf(ctx, block, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.Block, interface{}) uint64); ok {
		r0 = rf(ctx, block, dbTx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *etherman.Block, interface{}) error); ok {
		r1 = rf(ctx, block, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storageMock_AddBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBlock'
type storageMock_AddBlock_Call struct {
	*mock.Call
}

// AddBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - block *etherman.Block
//   - dbTx interface{}
func (_e *storageMock_Expecter) AddBlock(ctx interface{}, block interface{}, dbTx interface{}) *storageMock_AddBlock_Call {
	return &storageMock_AddBlock_Call{Call: _e.mock.On("AddBlock", ctx, block, dbTx)}
}

func (_c *storageMock_AddBlock_Call) Run(run func(ctx context.Context, block *etherman.Block, dbTx interface{})) *storageMock_AddBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*etherman.Block), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_AddBlock_Call) Return(_a0 uint64, _a1 error) *storageMock_AddBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *storageMock_AddBlock_Call) RunAndReturn(run func(context.Context, *etherman.Block, interface{}) (uint64, error)) *storageMock_AddBlock_Call {
	_c.Call.Return(run)
	return _c
}

// AddClaim provides a mock function with given fields: ctx, claim, dbTx
func (_m *storageMock) AddClaim(ctx context.Context, claim *etherman.Claim, dbTx interface{}) error {
	ret := _m.Called(ctx, claim, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddClaim")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.Claim, interface{}) error); ok {
		r0 = rf(ctx, claim, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_AddClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddClaim'
type storageMock_AddClaim_Call struct {
	*mock.Call
}

// AddClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - claim *etherman.Claim
//   - dbTx interface{}
func (_e *storageMock_Expecter) AddClaim(ctx interface{}, claim interface{}, dbTx interface{}) *storageMock_AddClaim_Call {
	return &storageMock_AddClaim_Call{Call: _e.mock.On("AddClaim", ctx, claim, dbTx)}
}

func (_c *storageMock_AddClaim_Call) Run(run func(ctx context.Context, claim *etherman.Claim, dbTx interface{})) *storageMock_AddClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*etherman.Claim), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_AddClaim_Call) Return(_a0 error) *storageMock_AddClaim_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_AddClaim_Call) RunAndReturn(run func(context.Context, *etherman.Claim, interface{}) error) *storageMock_AddClaim_Call {
	_c.Call.Return(run)
	return _c
}

// AddDeposit provides a mock function with given fields: ctx, deposit, dbTx
func (_m *storageMock) AddDeposit(ctx context.Context, deposit *etherman.Deposit, dbTx interface{}) (uint64, error) {
	ret := _m.Called(ctx, deposit, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddDeposit")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.Deposit, interface{}) (uint64, error)); ok {
		return rf(ctx, deposit, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.Deposit, interface{}) uint64); ok {
		r0 = rf(ctx, deposit, dbTx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *etherman.Deposit, interface{}) error); ok {
		r1 = rf(ctx, deposit, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storageMock_AddDeposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDeposit'
type storageMock_AddDeposit_Call struct {
	*mock.Call
}

// AddDeposit is a helper method to define mock.On call
//   - ctx context.Context
//   - deposit *etherman.Deposit
//   - dbTx interface{}
func (_e *storageMock_Expecter) AddDeposit(ctx interface{}, deposit interface{}, dbTx interface{}) *storageMock_AddDeposit_Call {
	return &storageMock_AddDeposit_Call{Call: _e.mock.On("AddDeposit", ctx, deposit, dbTx)}
}

func (_c *storageMock_AddDeposit_Call) Run(run func(ctx context.Context, deposit *etherman.Deposit, dbTx interface{})) *storageMock_AddDeposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*etherman.Deposit), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_AddDeposit_Call) Return(_a0 uint64, _a1 error) *storageMock_AddDeposit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *storageMock_AddDeposit_Call) RunAndReturn(run func(context.Context, *etherman.Deposit, interface{}) (uint64, error)) *storageMock_AddDeposit_Call {
	_c.Call.Return(run)
	return _c
}

// AddGlobalExitRoot provides a mock function with given fields: ctx, exitRoot, dbTx
func (_m *storageMock) AddGlobalExitRoot(ctx context.Context, exitRoot *etherman.GlobalExitRoot, dbTx interface{}) error {
	ret := _m.Called(ctx, exitRoot, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddGlobalExitRoot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.GlobalExitRoot, interface{}) error); ok {
		r0 = rf(ctx, exitRoot, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_AddGlobalExitRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGlobalExitRoot'
type storageMock_AddGlobalExitRoot_Call struct {
	*mock.Call
}

// AddGlobalExitRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - exitRoot *etherman.GlobalExitRoot
//   - dbTx interface{}
func (_e *storageMock_Expecter) AddGlobalExitRoot(ctx interface{}, exitRoot interface{}, dbTx interface{}) *storageMock_AddGlobalExitRoot_Call {
	return &storageMock_AddGlobalExitRoot_Call{Call: _e.mock.On("AddGlobalExitRoot", ctx, exitRoot, dbTx)}
}

func (_c *storageMock_AddGlobalExitRoot_Call) Run(run func(ctx context.Context, exitRoot *etherman.GlobalExitRoot, dbTx interface{})) *storageMock_AddGlobalExitRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*etherman.GlobalExitRoot), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_AddGlobalExitRoot_Call) Return(_a0 error) *storageMock_AddGlobalExitRoot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_AddGlobalExitRoot_Call) RunAndReturn(run func(context.Context, *etherman.GlobalExitRoot, interface{}) error) *storageMock_AddGlobalExitRoot_Call {
	_c.Call.Return(run)
	return _c
}

// AddRemoveL2GER provides a mock function with given fields: ctx, globalExitRoot, dbTx
func (_m *storageMock) AddRemoveL2GER(ctx context.Context, globalExitRoot etherman.GlobalExitRoot, dbTx interface{}) error {
	ret := _m.Called(ctx, globalExitRoot, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddRemoveL2GER")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, etherman.GlobalExitRoot, interface{}) error); ok {
		r0 = rf(ctx, globalExitRoot, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_AddRemoveL2GER_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRemoveL2GER'
type storageMock_AddRemoveL2GER_Call struct {
	*mock.Call
}

// AddRemoveL2GER is a helper method to define mock.On call
//   - ctx context.Context
//   - globalExitRoot etherman.GlobalExitRoot
//   - dbTx interface{}
func (_e *storageMock_Expecter) AddRemoveL2GER(ctx interface{}, globalExitRoot interface{}, dbTx interface{}) *storageMock_AddRemoveL2GER_Call {
	return &storageMock_AddRemoveL2GER_Call{Call: _e.mock.On("AddRemoveL2GER", ctx, globalExitRoot, dbTx)}
}

func (_c *storageMock_AddRemoveL2GER_Call) Run(run func(ctx context.Context, globalExitRoot etherman.GlobalExitRoot, dbTx interface{})) *storageMock_AddRemoveL2GER_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(etherman.GlobalExitRoot), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_AddRemoveL2GER_Call) Return(_a0 error) *storageMock_AddRemoveL2GER_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_AddRemoveL2GER_Call) RunAndReturn(run func(context.Context, etherman.GlobalExitRoot, interface{}) error) *storageMock_AddRemoveL2GER_Call {
	_c.Call.Return(run)
	return _c
}

// AddSetClaim provides a mock function with given fields: ctx, setClaim, dbTx
func (_m *storageMock) AddSetClaim(ctx context.Context, setClaim *etherman.SetClaim, dbTx interface{}) error {
	ret := _m.Called(ctx, setClaim, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddSetClaim")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.SetClaim, interface{}) error); ok {
		r0 = rf(ctx, setClaim, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_AddSetClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSetClaim'
type storageMock_AddSetClaim_Call struct {
	*mock.Call
}

// AddSetClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - setClaim *etherman.SetClaim
//   - dbTx interface{}
func (_e *storageMock_Expecter) AddSetClaim(ctx interface{}, setClaim interface{}, dbTx interface{}) *storageMock_AddSetClaim_Call {
	return &storageMock_AddSetClaim_Call{Call: _e.mock.On("AddSetClaim", ctx, setClaim, dbTx)}
}

func (_c *storageMock_AddSetClaim_Call) Run(run func(ctx context.Context, setClaim *etherman.SetClaim, dbTx interface{})) *storageMock_AddSetClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*etherman.SetClaim), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_AddSetClaim_Call) Return(_a0 error) *storageMock_AddSetClaim_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_AddSetClaim_Call) RunAndReturn(run func(context.Context, *etherman.SetClaim, interface{}) error) *storageMock_AddSetClaim_Call {
	_c.Call.Return(run)
	return _c
}

// AddSyncStatus provides a mock function with given fields: ctx, syncStatus, dbTx
func (_m *storageMock) AddSyncStatus(ctx context.Context, syncStatus etherman.SyncStatus, dbTx interface{}) error {
	ret := _m.Called(ctx, syncStatus, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddSyncStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, etherman.SyncStatus, interface{}) error); ok {
		r0 = rf(ctx, syncStatus, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_AddSyncStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSyncStatus'
type storageMock_AddSyncStatus_Call struct {
	*mock.Call
}

// AddSyncStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - syncStatus etherman.SyncStatus
//   - dbTx interface{}
func (_e *storageMock_Expecter) AddSyncStatus(ctx interface{}, syncStatus interface{}, dbTx interface{}) *storageMock_AddSyncStatus_Call {
	return &storageMock_AddSyncStatus_Call{Call: _e.mock.On("AddSyncStatus", ctx, syncStatus, dbTx)}
}

func (_c *storageMock_AddSyncStatus_Call) Run(run func(ctx context.Context, syncStatus etherman.SyncStatus, dbTx interface{})) *storageMock_AddSyncStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(etherman.SyncStatus), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_AddSyncStatus_Call) Return(_a0 error) *storageMock_AddSyncStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_AddSyncStatus_Call) RunAndReturn(run func(context.Context, etherman.SyncStatus, interface{}) error) *storageMock_AddSyncStatus_Call {
	_c.Call.Return(run)
	return _c
}

// AddTokenWrapped provides a mock function with given fields: ctx, tokenWrapped, dbTx
func (_m *storageMock) AddTokenWrapped(ctx context.Context, tokenWrapped *etherman.TokenWrapped, dbTx interface{}) error {
	ret := _m.Called(ctx, tokenWrapped, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddTokenWrapped")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.TokenWrapped, interface{}) error); ok {
		r0 = rf(ctx, tokenWrapped, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_AddTokenWrapped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTokenWrapped'
type storageMock_AddTokenWrapped_Call struct {
	*mock.Call
}

// AddTokenWrapped is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenWrapped *etherman.TokenWrapped
//   - dbTx interface{}
func (_e *storageMock_Expecter) AddTokenWrapped(ctx interface{}, tokenWrapped interface{}, dbTx interface{}) *storageMock_AddTokenWrapped_Call {
	return &storageMock_AddTokenWrapped_Call{Call: _e.mock.On("AddTokenWrapped", ctx, tokenWrapped, dbTx)}
}

func (_c *storageMock_AddTokenWrapped_Call) Run(run func(ctx context.Context, tokenWrapped *etherman.TokenWrapped, dbTx interface{})) *storageMock_AddTokenWrapped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*etherman.TokenWrapped), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_AddTokenWrapped_Call) Return(_a0 error) *storageMock_AddTokenWrapped_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_AddTokenWrapped_Call) RunAndReturn(run func(context.Context, *etherman.TokenWrapped, interface{}) error) *storageMock_AddTokenWrapped_Call {
	_c.Call.Return(run)
	return _c
}

// AddTrustedGlobalExitRoot provides a mock function with given fields: ctx, trustedExitRoot, dbTx
func (_m *storageMock) AddTrustedGlobalExitRoot(ctx context.Context, trustedExitRoot *etherman.GlobalExitRoot, dbTx interface{}) (bool, error) {
	ret := _m.Called(ctx, trustedExitRoot, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddTrustedGlobalExitRoot")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.GlobalExitRoot, interface{}) (bool, error)); ok {
		return rf(ctx, trustedExitRoot, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.GlobalExitRoot, interface{}) bool); ok {
		r0 = rf(ctx, trustedExitRoot, dbTx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *etherman.GlobalExitRoot, interface{}) error); ok {
		r1 = rf(ctx, trustedExitRoot, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storageMock_AddTrustedGlobalExitRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTrustedGlobalExitRoot'
type storageMock_AddTrustedGlobalExitRoot_Call struct {
	*mock.Call
}

// AddTrustedGlobalExitRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - trustedExitRoot *etherman.GlobalExitRoot
//   - dbTx interface{}
func (_e *storageMock_Expecter) AddTrustedGlobalExitRoot(ctx interface{}, trustedExitRoot interface{}, dbTx interface{}) *storageMock_AddTrustedGlobalExitRoot_Call {
	return &storageMock_AddTrustedGlobalExitRoot_Call{Call: _e.mock.On("AddTrustedGlobalExitRoot", ctx, trustedExitRoot, dbTx)}
}

func (_c *storageMock_AddTrustedGlobalExitRoot_Call) Run(run func(ctx context.Context, trustedExitRoot *etherman.GlobalExitRoot, dbTx interface{})) *storageMock_AddTrustedGlobalExitRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*etherman.GlobalExitRoot), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_AddTrustedGlobalExitRoot_Call) Return(_a0 bool, _a1 error) *storageMock_AddTrustedGlobalExitRoot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *storageMock_AddTrustedGlobalExitRoot_Call) RunAndReturn(run func(context.Context, *etherman.GlobalExitRoot, interface{}) (bool, error)) *storageMock_AddTrustedGlobalExitRoot_Call {
	_c.Call.Return(run)
	return _c
}

// AddUnsetClaim provides a mock function with given fields: ctx, unsetClaim, dbTx
func (_m *storageMock) AddUnsetClaim(ctx context.Context, unsetClaim *etherman.UnsetClaim, dbTx interface{}) error {
	ret := _m.Called(ctx, unsetClaim, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddUnsetClaim")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.UnsetClaim, interface{}) error); ok {
		r0 = rf(ctx, unsetClaim, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_AddUnsetClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUnsetClaim'
type storageMock_AddUnsetClaim_Call struct {
	*mock.Call
}

// AddUnsetClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - unsetClaim *etherman.UnsetClaim
//   - dbTx interface{}
func (_e *storageMock_Expecter) AddUnsetClaim(ctx interface{}, unsetClaim interface{}, dbTx interface{}) *storageMock_AddUnsetClaim_Call {
	return &storageMock_AddUnsetClaim_Call{Call: _e.mock.On("AddUnsetClaim", ctx, unsetClaim, dbTx)}
}

func (_c *storageMock_AddUnsetClaim_Call) Run(run func(ctx context.Context, unsetClaim *etherman.UnsetClaim, dbTx interface{})) *storageMock_AddUnsetClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*etherman.UnsetClaim), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_AddUnsetClaim_Call) Return(_a0 error) *storageMock_AddUnsetClaim_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_AddUnsetClaim_Call) RunAndReturn(run func(context.Context, *etherman.UnsetClaim, interface{}) error) *storageMock_AddUnsetClaim_Call {
	_c.Call.Return(run)
	return _c
}

// BeginDBTransaction provides a mock function with given fields: ctx
func (_m *storageMock) BeginDBTransaction(ctx context.Context) (interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginDBTransaction")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storageMock_BeginDBTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginDBTransaction'
type storageMock_BeginDBTransaction_Call struct {
	*mock.Call
}

// BeginDBTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *storageMock_Expecter) BeginDBTransaction(ctx interface{}) *storageMock_BeginDBTransaction_Call {
	return &storageMock_BeginDBTransaction_Call{Call: _e.mock.On("BeginDBTransaction", ctx)}
}

func (_c *storageMock_BeginDBTransaction_Call) Run(run func(ctx context.Context)) *storageMock_BeginDBTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *storageMock_BeginDBTransaction_Call) Return(_a0 interface{}, _a1 error) *storageMock_BeginDBTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *storageMock_BeginDBTransaction_Call) RunAndReturn(run func(context.Context) (interface{}, error)) *storageMock_BeginDBTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// CheckIfRootExists provides a mock function with given fields: ctx, root, network, dbTx
func (_m *storageMock) CheckIfRootExists(ctx context.Context, root []byte, network uint32, dbTx interface{}) (bool, error) {
	ret := _m.Called(ctx, root, network, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for CheckIfRootExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, uint32, interface{}) (bool, error)); ok {
		return rf(ctx, root, network, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, uint32, interface{}) bool); ok {
		r0 = rf(ctx, root, network, dbTx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, uint32, interface{}) error); ok {
		r1 = rf(ctx, root, network, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storageMock_CheckIfRootExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckIfRootExists'
type storageMock_CheckIfRootExists_Call struct {
	*mock.Call
}

// CheckIfRootExists is a helper method to define mock.On call
//   - ctx context.Context
//   - root []byte
//   - network uint32
//   - dbTx interface{}
func (_e *storageMock_Expecter) CheckIfRootExists(ctx interface{}, root interface{}, network interface{}, dbTx interface{}) *storageMock_CheckIfRootExists_Call {
	return &storageMock_CheckIfRootExists_Call{Call: _e.mock.On("CheckIfRootExists", ctx, root, network, dbTx)}
}

func (_c *storageMock_CheckIfRootExists_Call) Run(run func(ctx context.Context, root []byte, network uint32, dbTx interface{})) *storageMock_CheckIfRootExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(uint32), args[3].(interface{}))
	})
	return _c
}

func (_c *storageMock_CheckIfRootExists_Call) Return(_a0 bool, _a1 error) *storageMock_CheckIfRootExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *storageMock_CheckIfRootExists_Call) RunAndReturn(run func(context.Context, []byte, uint32, interface{}) (bool, error)) *storageMock_CheckIfRootExists_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function with given fields: ctx, dbTx
func (_m *storageMock) Commit(ctx context.Context, dbTx interface{}) error {
	ret := _m.Called(ctx, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type storageMock_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - dbTx interface{}
func (_e *storageMock_Expecter) Commit(ctx interface{}, dbTx interface{}) *storageMock_Commit_Call {
	return &storageMock_Commit_Call{Call: _e.mock.On("Commit", ctx, dbTx)}
}

func (_c *storageMock_Commit_Call) Run(run func(ctx context.Context, dbTx interface{})) *storageMock_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *storageMock_Commit_Call) Return(_a0 error) *storageMock_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_Commit_Call) RunAndReturn(run func(context.Context, interface{}) error) *storageMock_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClaimByGlobalIndex provides a mock function with given fields: ctx, globalIndex, networkID, dbTx
func (_m *storageMock) DeleteClaimByGlobalIndex(ctx context.Context, globalIndex *big.Int, networkID uint32, dbTx interface{}) error {
	ret := _m.Called(ctx, globalIndex, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClaimByGlobalIndex")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int, uint32, interface{}) error); ok {
		r0 = rf(ctx, globalIndex, networkID, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_DeleteClaimByGlobalIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClaimByGlobalIndex'
type storageMock_DeleteClaimByGlobalIndex_Call struct {
	*mock.Call
}

// DeleteClaimByGlobalIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - globalIndex *big.Int
//   - networkID uint32
//   - dbTx interface{}
func (_e *storageMock_Expecter) DeleteClaimByGlobalIndex(ctx interface{}, globalIndex interface{}, networkID interface{}, dbTx interface{}) *storageMock_DeleteClaimByGlobalIndex_Call {
	return &storageMock_DeleteClaimByGlobalIndex_Call{Call: _e.mock.On("DeleteClaimByGlobalIndex", ctx, globalIndex, networkID, dbTx)}
}

func (_c *storageMock_DeleteClaimByGlobalIndex_Call) Run(run func(ctx context.Context, globalIndex *big.Int, networkID uint32, dbTx interface{})) *storageMock_DeleteClaimByGlobalIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*big.Int), args[2].(uint32), args[3].(interface{}))
	})
	return _c
}

func (_c *storageMock_DeleteClaimByGlobalIndex_Call) Return(_a0 error) *storageMock_DeleteClaimByGlobalIndex_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_DeleteClaimByGlobalIndex_Call) RunAndReturn(run func(context.Context, *big.Int, uint32, interface{}) error) *storageMock_DeleteClaimByGlobalIndex_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeposit provides a mock function with given fields: ctx, depositCounter, networkID, dbTx
func (_m *storageMock) GetDeposit(ctx context.Context, depositCounter uint32, networkID uint32, dbTx interface{}) (*etherman.Deposit, error) {
	ret := _m.Called(ctx, depositCounter, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetDeposit")
	}

	var r0 *etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, interface{}) (*etherman.Deposit, error)); ok {
		return rf(ctx, depositCounter, networkID, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, interface{}) *etherman.Deposit); ok {
		r0 = rf(ctx, depositCounter, networkID, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, interface{}) error); ok {
		r1 = rf(ctx, depositCounter, networkID, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storageMock_GetDeposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeposit'
type storageMock_GetDeposit_Call struct {
	*mock.Call
}

// GetDeposit is a helper method to define mock.On call
//   - ctx context.Context
//   - depositCounter uint32
//   - networkID uint32
//   - dbTx interface{}
func (_e *storageMock_Expecter) GetDeposit(ctx interface{}, depositCounter interface{}, networkID interface{}, dbTx interface{}) *storageMock_GetDeposit_Call {
	return &storageMock_GetDeposit_Call{Call: _e.mock.On("GetDeposit", ctx, depositCounter, networkID, dbTx)}
}

func (_c *storageMock_GetDeposit_Call) Run(run func(ctx context.Context, depositCounter uint32, networkID uint32, dbTx interface{})) *storageMock_GetDeposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(interface{}))
	})
	return _c
}

func (_c *storageMock_GetDeposit_Call) Return(_a0 *etherman.Deposit, _a1 error) *storageMock_GetDeposit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *storageMock_GetDeposit_Call) RunAndReturn(run func(context.Context, uint32, uint32, interface{}) (*etherman.Deposit, error)) *storageMock_GetDeposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetL1ExitRootByGER provides a mock function with given fields: ctx, ger, dbTx
func (_m *storageMock) GetL1ExitRootByGER(ctx context.Context, ger common.Hash, dbTx interface{}) (*etherman.GlobalExitRoot, error) {
	ret := _m.Called(ctx, ger, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetL1ExitRootByGER")
	}

	var r0 *etherman.GlobalExitRoot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, interface{}) (*etherman.GlobalExitRoot, error)); ok {
		return rf(ctx, ger, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, interface{}) *etherman.GlobalExitRoot); ok {
		r0 = rf(ctx, ger, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etherman.GlobalExitRoot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Hash, interface{}) error); ok {
		r1 = rf(ctx, ger, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storageMock_GetL1ExitRootByGER_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetL1ExitRootByGER'
type storageMock_GetL1ExitRootByGER_Call struct {
	*mock.Call
}

// GetL1ExitRootByGER is a helper method to define mock.On call
//   - ctx context.Context
//   - ger common.Hash
//   - dbTx interface{}
func (_e *storageMock_Expecter) GetL1ExitRootByGER(ctx interface{}, ger interface{}, dbTx interface{}) *storageMock_GetL1ExitRootByGER_Call {
	return &storageMock_GetL1ExitRootByGER_Call{Call: _e.mock.On("GetL1ExitRootByGER", ctx, ger, dbTx)}
}

func (_c *storageMock_GetL1ExitRootByGER_Call) Run(run func(ctx context.Context, ger common.Hash, dbTx interface{})) *storageMock_GetL1ExitRootByGER_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Hash), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_GetL1ExitRootByGER_Call) Return(_a0 *etherman.GlobalExitRoot, _a1 error) *storageMock_GetL1ExitRootByGER_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *storageMock_GetL1ExitRootByGER_Call) RunAndReturn(run func(context.Context, common.Hash, interface{}) (*etherman.GlobalExitRoot, error)) *storageMock_GetL1ExitRootByGER_Call {
	_c.Call.Return(run)
	return _c
}

// GetL2ExitRootsByGER provides a mock function with given fields: ctx, ger, dbTx
func (_m *storageMock) GetL2ExitRootsByGER(ctx context.Context, ger common.Hash, dbTx interface{}) ([]etherman.GlobalExitRoot, error) {
	ret := _m.Called(ctx, ger, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetL2ExitRootsByGER")
	}

	var r0 []etherman.GlobalExitRoot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, interface{}) ([]etherman.GlobalExitRoot, error)); ok {
		return rf(ctx, ger, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, interface{}) []etherman.GlobalExitRoot); ok {
		r0 = rf(ctx, ger, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]etherman.GlobalExitRoot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Hash, interface{}) error); ok {
		r1 = rf(ctx, ger, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storageMock_GetL2ExitRootsByGER_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetL2ExitRootsByGER'
type storageMock_GetL2ExitRootsByGER_Call struct {
	*mock.Call
}

// GetL2ExitRootsByGER is a helper method to define mock.On call
//   - ctx context.Context
//   - ger common.Hash
//   - dbTx interface{}
func (_e *storageMock_Expecter) GetL2ExitRootsByGER(ctx interface{}, ger interface{}, dbTx interface{}) *storageMock_GetL2ExitRootsByGER_Call {
	return &storageMock_GetL2ExitRootsByGER_Call{Call: _e.mock.On("GetL2ExitRootsByGER", ctx, ger, dbTx)}
}

func (_c *storageMock_GetL2ExitRootsByGER_Call) Run(run func(ctx context.Context, ger common.Hash, dbTx interface{})) *storageMock_GetL2ExitRootsByGER_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Hash), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_GetL2ExitRootsByGER_Call) Return(_a0 []etherman.GlobalExitRoot, _a1 error) *storageMock_GetL2ExitRootsByGER_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *storageMock_GetL2ExitRootsByGER_Call) RunAndReturn(run func(context.Context, common.Hash, interface{}) ([]etherman.GlobalExitRoot, error)) *storageMock_GetL2ExitRootsByGER_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastBlock provides a mock function with given fields: ctx, networkID, dbTx
func (_m *storageMock) GetLastBlock(ctx context.Context, networkID uint32, dbTx interface{}) (*etherman.Block, error) {
	ret := _m.Called(ctx, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastBlock")
	}

	var r0 *etherman.Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, interface{}) (*etherman.Block, error)); ok {
		return rf(ctx, networkID, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, interface{}) *etherman.Block); ok {
		r0 = rf(ctx, networkID, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etherman.Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, interface{}) error); ok {
		r1 = rf(ctx, networkID, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storageMock_GetLastBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastBlock'
type storageMock_GetLastBlock_Call struct {
	*mock.Call
}

// GetLastBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - networkID uint32
//   - dbTx interface{}
func (_e *storageMock_Expecter) GetLastBlock(ctx interface{}, networkID interface{}, dbTx interface{}) *storageMock_GetLastBlock_Call {
	return &storageMock_GetLastBlock_Call{Call: _e.mock.On("GetLastBlock", ctx, networkID, dbTx)}
}

func (_c *storageMock_GetLastBlock_Call) Run(run func(ctx context.Context, networkID uint32, dbTx interface{})) *storageMock_GetLastBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_GetLastBlock_Call) Return(_a0 *etherman.Block, _a1 error) *storageMock_GetLastBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *storageMock_GetLastBlock_Call) RunAndReturn(run func(context.Context, uint32, interface{}) (*etherman.Block, error)) *storageMock_GetLastBlock_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestL1SyncedExitRoot provides a mock function with given fields: ctx, dbTx
func (_m *storageMock) GetLatestL1SyncedExitRoot(ctx context.Context, dbTx interface{}) (*etherman.GlobalExitRoot, error) {
	ret := _m.Called(ctx, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestL1SyncedExitRoot")
	}

	var r0 *etherman.GlobalExitRoot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) (*etherman.GlobalExitRoot, error)); ok {
		return rf(ctx, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) *etherman.GlobalExitRoot); ok {
		r0 = rf(ctx, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etherman.GlobalExitRoot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}) error); ok {
		r1 = rf(ctx, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storageMock_GetLatestL1SyncedExitRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestL1SyncedExitRoot'
type storageMock_GetLatestL1SyncedExitRoot_Call struct {
	*mock.Call
}

// GetLatestL1SyncedExitRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - dbTx interface{}
func (_e *storageMock_Expecter) GetLatestL1SyncedExitRoot(ctx interface{}, dbTx interface{}) *storageMock_GetLatestL1SyncedExitRoot_Call {
	return &storageMock_GetLatestL1SyncedExitRoot_Call{Call: _e.mock.On("GetLatestL1SyncedExitRoot", ctx, dbTx)}
}

func (_c *storageMock_GetLatestL1SyncedExitRoot_Call) Run(run func(ctx context.Context, dbTx interface{})) *storageMock_GetLatestL1SyncedExitRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *storageMock_GetLatestL1SyncedExitRoot_Call) Return(_a0 *etherman.GlobalExitRoot, _a1 error) *storageMock_GetLatestL1SyncedExitRoot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *storageMock_GetLatestL1SyncedExitRoot_Call) RunAndReturn(run func(context.Context, interface{}) (*etherman.GlobalExitRoot, error)) *storageMock_GetLatestL1SyncedExitRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestTrustedExitRoot provides a mock function with given fields: ctx, networkID, dbTx
func (_m *storageMock) GetLatestTrustedExitRoot(ctx context.Context, networkID uint32, dbTx interface{}) (*etherman.GlobalExitRoot, error) {
	ret := _m.Called(ctx, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestTrustedExitRoot")
	}

	var r0 *etherman.GlobalExitRoot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, interface{}) (*etherman.GlobalExitRoot, error)); ok {
		return rf(ctx, networkID, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, interface{}) *etherman.GlobalExitRoot); ok {
		r0 = rf(ctx, networkID, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etherman.GlobalExitRoot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, interface{}) error); ok {
		r1 = rf(ctx, networkID, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storageMock_GetLatestTrustedExitRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestTrustedExitRoot'
type storageMock_GetLatestTrustedExitRoot_Call struct {
	*mock.Call
}

// GetLatestTrustedExitRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - networkID uint32
//   - dbTx interface{}
func (_e *storageMock_Expecter) GetLatestTrustedExitRoot(ctx interface{}, networkID interface{}, dbTx interface{}) *storageMock_GetLatestTrustedExitRoot_Call {
	return &storageMock_GetLatestTrustedExitRoot_Call{Call: _e.mock.On("GetLatestTrustedExitRoot", ctx, networkID, dbTx)}
}

func (_c *storageMock_GetLatestTrustedExitRoot_Call) Run(run func(ctx context.Context, networkID uint32, dbTx interface{})) *storageMock_GetLatestTrustedExitRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_GetLatestTrustedExitRoot_Call) Return(_a0 *etherman.GlobalExitRoot, _a1 error) *storageMock_GetLatestTrustedExitRoot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *storageMock_GetLatestTrustedExitRoot_Call) RunAndReturn(run func(context.Context, uint32, interface{}) (*etherman.GlobalExitRoot, error)) *storageMock_GetLatestTrustedExitRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetNumberDeposits provides a mock function with given fields: ctx, origNetworkID, blockNumber, dbTx
func (_m *storageMock) GetNumberDeposits(ctx context.Context, origNetworkID uint32, blockNumber uint64, dbTx interface{}) (uint32, error) {
	ret := _m.Called(ctx, origNetworkID, blockNumber, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetNumberDeposits")
	}

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64, interface{}) (uint32, error)); ok {
		return rf(ctx, origNetworkID, blockNumber, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64, interface{}) uint32); ok {
		r0 = rf(ctx, origNetworkID, blockNumber, dbTx)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint64, interface{}) error); ok {
		r1 = rf(ctx, origNetworkID, blockNumber, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storageMock_GetNumberDeposits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNumberDeposits'
type storageMock_GetNumberDeposits_Call struct {
	*mock.Call
}

// GetNumberDeposits is a helper method to define mock.On call
//   - ctx context.Context
//   - origNetworkID uint32
//   - blockNumber uint64
//   - dbTx interface{}
func (_e *storageMock_Expecter) GetNumberDeposits(ctx interface{}, origNetworkID interface{}, blockNumber interface{}, dbTx interface{}) *storageMock_GetNumberDeposits_Call {
	return &storageMock_GetNumberDeposits_Call{Call: _e.mock.On("GetNumberDeposits", ctx, origNetworkID, blockNumber, dbTx)}
}

func (_c *storageMock_GetNumberDeposits_Call) Run(run func(ctx context.Context, origNetworkID uint32, blockNumber uint64, dbTx interface{})) *storageMock_GetNumberDeposits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint64), args[3].(interface{}))
	})
	return _c
}

func (_c *storageMock_GetNumberDeposits_Call) Return(_a0 uint32, _a1 error) *storageMock_GetNumberDeposits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *storageMock_GetNumberDeposits_Call) RunAndReturn(run func(context.Context, uint32, uint64, interface{}) (uint32, error)) *storageMock_GetNumberDeposits_Call {
	_c.Call.Return(run)
	return _c
}

// GetPreviousBlock provides a mock function with given fields: ctx, networkID, offset, dbTx
func (_m *storageMock) GetPreviousBlock(ctx context.Context, networkID uint32, offset uint64, dbTx interface{}) (etherman.Block, error) {
	ret := _m.Called(ctx, networkID, offset, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetPreviousBlock")
	}

	var r0 etherman.Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64, interface{}) (etherman.Block, error)); ok {
		return rf(ctx, networkID, offset, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64, interface{}) etherman.Block); ok {
		r0 = rf(ctx, networkID, offset, dbTx)
	} else {
		r0 = ret.Get(0).(etherman.Block)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint64, interface{}) error); ok {
		r1 = rf(ctx, networkID, offset, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storageMock_GetPreviousBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPreviousBlock'
type storageMock_GetPreviousBlock_Call struct {
	*mock.Call
}

// GetPreviousBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - networkID uint32
//   - offset uint64
//   - dbTx interface{}
func (_e *storageMock_Expecter) GetPreviousBlock(ctx interface{}, networkID interface{}, offset interface{}, dbTx interface{}) *storageMock_GetPreviousBlock_Call {
	return &storageMock_GetPreviousBlock_Call{Call: _e.mock.On("GetPreviousBlock", ctx, networkID, offset, dbTx)}
}

func (_c *storageMock_GetPreviousBlock_Call) Run(run func(ctx context.Context, networkID uint32, offset uint64, dbTx interface{})) *storageMock_GetPreviousBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint64), args[3].(interface{}))
	})
	return _c
}

func (_c *storageMock_GetPreviousBlock_Call) Return(_a0 etherman.Block, _a1 error) *storageMock_GetPreviousBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *storageMock_GetPreviousBlock_Call) RunAndReturn(run func(context.Context, uint32, uint64, interface{}) (etherman.Block, error)) *storageMock_GetPreviousBlock_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with given fields: ctx, blockNumber, networkID, dbTx
func (_m *storageMock) Reset(ctx context.Context, blockNumber uint64, networkID uint32, dbTx interface{}) error {
	ret := _m.Called(ctx, blockNumber, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint32, interface{}) error); ok {
		r0 = rf(ctx, blockNumber, networkID, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type storageMock_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNumber uint64
//   - networkID uint32
//   - dbTx interface{}
func (_e *storageMock_Expecter) Reset(ctx interface{}, blockNumber interface{}, networkID interface{}, dbTx interface{}) *storageMock_Reset_Call {
	return &storageMock_Reset_Call{Call: _e.mock.On("Reset", ctx, blockNumber, networkID, dbTx)}
}

func (_c *storageMock_Reset_Call) Run(run func(ctx context.Context, blockNumber uint64, networkID uint32, dbTx interface{})) *storageMock_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint32), args[3].(interface{}))
	})
	return _c
}

func (_c *storageMock_Reset_Call) Return(_a0 error) *storageMock_Reset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_Reset_Call) RunAndReturn(run func(context.Context, uint64, uint32, interface{}) error) *storageMock_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// ResetDeposits provides a mock function with given fields: ctx, depositCount, networkID, dbTx
func (_m *storageMock) ResetDeposits(ctx context.Context, depositCount uint32, networkID uint32, dbTx interface{}) error {
	ret := _m.Called(ctx, depositCount, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for ResetDeposits")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, interface{}) error); ok {
		r0 = rf(ctx, depositCount, networkID, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_ResetDeposits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetDeposits'
type storageMock_ResetDeposits_Call struct {
	*mock.Call
}

// ResetDeposits is a helper method to define mock.On call
//   - ctx context.Context
//   - depositCount uint32
//   - networkID uint32
//   - dbTx interface{}
func (_e *storageMock_Expecter) ResetDeposits(ctx interface{}, depositCount interface{}, networkID interface{}, dbTx interface{}) *storageMock_ResetDeposits_Call {
	return &storageMock_ResetDeposits_Call{Call: _e.mock.On("ResetDeposits", ctx, depositCount, networkID, dbTx)}
}

func (_c *storageMock_ResetDeposits_Call) Run(run func(ctx context.Context, depositCount uint32, networkID uint32, dbTx interface{})) *storageMock_ResetDeposits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(interface{}))
	})
	return _c
}

func (_c *storageMock_ResetDeposits_Call) Return(_a0 error) *storageMock_ResetDeposits_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_ResetDeposits_Call) RunAndReturn(run func(context.Context, uint32, uint32, interface{}) error) *storageMock_ResetDeposits_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx, dbTx
func (_m *storageMock) Rollback(ctx context.Context, dbTx interface{}) error {
	ret := _m.Called(ctx, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type storageMock_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
//   - dbTx interface{}
func (_e *storageMock_Expecter) Rollback(ctx interface{}, dbTx interface{}) *storageMock_Rollback_Call {
	return &storageMock_Rollback_Call{Call: _e.mock.On("Rollback", ctx, dbTx)}
}

func (_c *storageMock_Rollback_Call) Run(run func(ctx context.Context, dbTx interface{})) *storageMock_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *storageMock_Rollback_Call) Return(_a0 error) *storageMock_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_Rollback_Call) RunAndReturn(run func(context.Context, interface{}) error) *storageMock_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateL2GER provides a mock function with given fields: ctx, ger, dbTx
func (_m *storageMock) UpdateL2GER(ctx context.Context, ger etherman.GlobalExitRoot, dbTx interface{}) error {
	ret := _m.Called(ctx, ger, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateL2GER")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, etherman.GlobalExitRoot, interface{}) error); ok {
		r0 = rf(ctx, ger, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// storageMock_UpdateL2GER_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateL2GER'
type storageMock_UpdateL2GER_Call struct {
	*mock.Call
}

// UpdateL2GER is a helper method to define mock.On call
//   - ctx context.Context
//   - ger etherman.GlobalExitRoot
//   - dbTx interface{}
func (_e *storageMock_Expecter) UpdateL2GER(ctx interface{}, ger interface{}, dbTx interface{}) *storageMock_UpdateL2GER_Call {
	return &storageMock_UpdateL2GER_Call{Call: _e.mock.On("UpdateL2GER", ctx, ger, dbTx)}
}

func (_c *storageMock_UpdateL2GER_Call) Run(run func(ctx context.Context, ger etherman.GlobalExitRoot, dbTx interface{})) *storageMock_UpdateL2GER_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(etherman.GlobalExitRoot), args[2].(interface{}))
	})
	return _c
}

func (_c *storageMock_UpdateL2GER_Call) Return(_a0 error) *storageMock_UpdateL2GER_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *storageMock_UpdateL2GER_Call) RunAndReturn(run func(context.Context, etherman.GlobalExitRoot, interface{}) error) *storageMock_UpdateL2GER_Call {
	_c.Call.Return(run)
	return _c
}

// newStorageMock creates a new instance of storageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *storageMock {
	mock := &storageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
